### ISSUE TITLE
confusing example given for Organisation Role

### ISSUE THREAD

**Issue by monkeypants** [ato-team/business-registries-rest-api-specification#1]
The description of Organisation Roles says: "A role defines the characteristics of a relationship between parties (individuals and organisations)." and the response example from `GET /organisations/{partyId}/roles/{roleId}` looks a bit like this (I changed the party IDs):
```json
{
  "id": "123e4567-e89b-12d3-a456-426655440000",
  "fromPartyId": "party-x",
  "fromPartyRoleType": "Director",
  "toPartyId": "party-y",
  "toPartyRoleType": "Office Bearer",
  "relationshipType": "Office Holder",
  "fromDate": "2016-01-13T09:05:06+10:00",
  "toDate": ""
}
```

Unfortunately this made me think.

Does this mean:
 * This {id} is an Office Holder relationship (effective from {fromDate})
 * party-x is a Director of party-y
 * party-y is an Office Bearer of party-x (implied, perhaps incorrectly)

There's something confusing about the semantics here. Using "from" and "to" implies a simple directed relationship, and this interpretation makes sense when looking at fromPartyRoleType ("party-x is a Director of party-y"). But, applying this interpretation to the fromPartyRoleType side doesn't make sense; I thought all Directors are Office Holders (but not all office holders are Directors - a Director is a subtype of Office Holder). Right? in this Office Holder relationship, is it not the case that the Director and the Office Bearer are the same person (party-x)?  

Perhaps the toPartyRoleType should be renamed to something like "Office Held", so:

 * party-x is a Director of party-y
 * party-y has Office Held by party-x

Or, perhaps I misunderstand the semantic relationship between fromPartRoleType and toPartyRoleType, or Office Holding relationships generally...

Please provide more explanation about Organisation Roles, or find a less confusing example.

**Comment by Robinyo** [comment]
Yes, sorry it's very much a "work in progress".

The `Director` role is an interesting one. So let's start with an easier one:

| Party                           | Role     | Relationship     | Role       | Party         |
| ------------------------------- | -------- | ---------------- | ---------- | ------------- |
| Springfield Nuclear Power Plant | Employer | Employment       | Employee   | Homer Simpson |

```
The response sample from GET /organisations/{partyId}/roles/{roleId}

[
  {
  "id": "1234",
  "fromPartyRoleType": "Employee",
  "toPartyId": "6789",
  "toPartyRoleType": "Employer",
  "relationshipType": "Employment",
  "fromDate": "2016-01-13T09:05:06+10:00",
  "toDate": ""
  }
]
```

Which means, that Homer `{partyId}` is an `Employee` (fromPartyRoleType) and his `Employer` (toPartyRoleType) is Springfield Nuclear Power Plant (toPartyId). And, that it's an `Employment` (relationshipType).

The `Director` role is an interesting one due to the fact that its mostly thought of and/or described from the perspective of the office holder/office bearer rather than from the perspective of the organisation.

| Party                           | Role     | Relationship     | Role       | Party         |
| ------------------------------- | -------- | ---------------- | ---------- | ------------- |
| Springfield Nuclear Power Plant | Employer | Employment       | Employee   | Homer Simpson |
| Springfield Nuclear Power Plant | Employer | Office Holder    | Director   | Mr Burns      |
| Springfield Nuclear Power Plant |          | Office Holder    | Director   | Fat Tony      |
| Springfield Nuclear Power Plant | Customer | Service Provider | Accountant | Dan Gillick   |

So, if Mr Burns is a `Director` and an `Employee` of the Springfield Nuclear Power Plant. Then we can say that Springfield Nuclear Power Plant is his 'Employer'. However, if Fat Tony is a `Director` (albeit a silent one) but not an `Employee` of the Springfield Nuclear Power Plant then what role is Springfield Nuclear Power Plant playing in the relationship?

**Comment by Robinyo** [comment]
I have provided updated examples for Individual roles and Organisation roles:
- https://ato-team.github.io/business-registries-rest-api-specification/#tag/Individuals-Roles
- https://ato-team.github.io/business-registries-rest-api-specification/#tag/Organisations-Roles

**Comment by Robinyo** [comment]
And, I've updated the request and response schema:
```
{
  "id": "123e4567-e89b-12d3-a456-9876543210",
  "partyRoleType": "Employee",
  "relatedPartyId": "123e4567-e89b-12d3-a456-9876543211",
  "relatedPartyRoleType": "Employer",
  "relationshipType": "Employment",
  "fromDate": "2016-01-13T09:05:06+10:00",
  "toDate": ""
}
```

**Comment by monkeypants** [comment]
> if Fat Tony is a Director (albeit a silent one) but not an Employee of the Springfield Nuclear Power Plant then what role is Springfield Nuclear Power Plant playing in the relationship?

We have names for both ends of the "Employment" relationship (employee/employee). Other directed relationships also have both ends named (franchisor/franchisee, perpetrator/victim, etc). But I don't know a word to label "is director of" and "has the director" ends of the Director relationship. There's nothing different or special about the relationship, except that we lack those labels.

Suggestion: Perhaps naming the ends is redundant? If you renamed Employment to "is Employed by", and read "from" left "to" right, `Homer Simpson, is Employed by, Springfield Nuclear Power Plant`, then you wouldn't need to label the ends of the relationship. A rose by any other name...

**Comment by Robinyo** [comment]
After some more thought, the reciprocal role name for `Director` should be the Organisation's "Legal Entity Type", for example, `Company`. And, like wise for `Membership` and `Partnership`:

      | Party         | Role           | Relationship     | Role         | Party                           |
      | ------------- | -------------- | ---------------- | ------------ | ------------------------------- |
      | Homer Simpson | Husband        | Marriage         | Wife         | Marge Simpson                   |
      | Homer Simpson | Employee       | Employment       | Employer     | Springfield Nuclear Power Plant |
      | Homer Simpson | Safety Officer | Colleague        | Supervisor   | Carl Carlson                    |
      | Homer Simpson | Director       | Directorship     | Company      | Mr Plow                         |
      | Homer Simpson | Employee       | Employment       | Employer     | Mr Plow                         |
      | Homer Simpson | Member         | Membership       | Organisation | Stonecutters                    |
      | Homer Simpson | Partner        | Partnership      | Partnership  | The Be Sharps                   |

Being able to name the reciprocal role is very important, particularly when we need to associate additional attributes (e.g., an alternate name or Business Trading Name) with a role.

**Comment by monkeypants** [comment]
Is there a definitive list of types of Relationships, what there reciprocal roles are called (and what they mean)? Does it change over time?

**Comment by Robinyo** [comment]
Is there a definitive list of types of Relationships, what there reciprocal roles are called (and what they mean)?

Not yet, it's being worked on by another ATO team who are also engaging ASIC and the Department of Industry. Yes, it will change (slowly) over time.

**Comment by monkeypants** [comment]
As an API user, I won't want to try and specify invalid relationships.
```
Homer Simpson is Safety Officer of Marriage to Supervisor Marge Simpson"
```
That probably deserves an error response specification (e.g. `403 Forbidden`) on the API.

If would be nice if the API user could discover rules about valid combinations without resorting to trial and error. If it didn't change over time, hard-coding them in the API spec would be a strait-forward. But since they are expected to change over time, maybe it would be nice if the API was self-describing in this regard. Do you think that might be an option? the API implementation will need to know the rules if it is going to implement them.

**Comment by Robinyo** [comment]
Yes, I agree (as the REST API will be consumed by different UI's) the set of valid values must be discoverable.

I have been looking for some good REST API (metadata) examples, so far I have found: https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-discovering-meta-data-for-creating-issues

Not happy with their URI naming, still considering options, for example:

`GET /roles?partType=individual&classification=relationship`

(working on this right now)

Currently the spec includes a `400 The client specified an invalid argument` error response.

See: https://ato-team.github.io/business-registries-rest-api-specification/#tag/Individuals-Roles%2Fpaths%2F~1individuals~1%7BpartyId%7D~1roles%2Fpost

**Comment by monkeypants** [comment]
KISS: `GET /relationships/` -> list of relationship types, including rule table and role definitions.

**Comment by Robinyo** [comment]
Genders: https://ato-team.github.io/business-registries-rest-api-specification/#tag/Genders
Roles: https://ato-team.github.io/business-registries-rest-api-specification/#tag/Roles

**Comment by monkeypants** [comment]
If you update the descriptions in Individuals-Roles and Organisations-Roles (reference the Roles method), I would consider this ticket ready to close. Thanks for being so responsive!

**Comment by Robinyo** [comment]
Thanks for all your feedback, much appreciated :)

See: https://ato-team.github.io/business-registries-rest-api-specification/#section/Overview/Metadata

And:
- https://ato-team.github.io/business-registries-rest-api-specification/#tag/Individuals-Roles
- https://ato-team.github.io/business-registries-rest-api-specification/#tag/Organisations-Roles
