### ISSUE TITLE
how to get an API key?

### ISSUE THREAD

**Issue by monkeypants** [ato-team/business-registries-rest-api-specification#2]
The Authentication subsection of the Overview part of the spec says "When you sign up for an account, you are given your first API key."

OK, great! I want one, how do I get one? Some place near the top of the document should tell me this.

And how does API key authorisation work (what can any given API key holder do with their keys)? Maybe there should be comments about this in the documentation of relevant methods.

**Comment by Robinyo** [comment]
Yes, sorry it's very much a "work in progress".

Were also hoping to use something like: https://gelato.io/

**Comment by monkeypants** [comment]
My question is more about "To whom will api keys be available, for what purposes, and under what circumstances?"

A developer portal and API gateway make sense. Kong/Gelato and so there will be some sort of mechanism for getting an api key.

**Comment by monkeypants** [comment]
open/close was fat finger
